name: Build Docker Image and Save as Tar

on:
  push:
    branches:
      - main

jobs:
  build-and-save-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image and save as tar
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          output: type=tar,dest=image.tar

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image-tar
          path: image.tar
